title: Rec Framework
description: Rec Data Processing Framework
github:
  repository_url: https://github.com/rec-framework
  repository_name: Rec Framework
  owner_url: https://github.com/kenpusney
  owner_name: Kimmy Leo
theme: jekyll-theme-minimal
